import boto3
import os
import sys


base_dir = os.path.dirname(os.path.abspath(__file__))
DOWNLOAD_PATH = os.path.join(base_dir, "Texts")
os.makedirs(DOWNLOAD_PATH, exist_ok=True)

s3 = boto3.client("s3",endpoint_url = 'https://'+'minio.lab.sspcloud.fr',
                  aws_access_key_id= '543TEHSBTMDJWN0JEN5B', 
                  aws_secret_access_key= 'Rn0+Yg2hpjdKnSCE7QCIdpKC19R5f5islmkDVBw+', 
                  aws_session_token = 'eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJhY2Nlc3NLZXkiOiI1NDNURUhTQlRNREpXTjBKRU41QiIsImFsbG93ZWQtb3JpZ2lucyI6WyIqIl0sImF1ZCI6WyJtaW5pby1kYXRhbm9kZSIsIm9ueXhpYSIsImFjY291bnQiXSwiYXV0aF90aW1lIjoxNzcxODQwNjQ4LCJhenAiOiJvbnl4aWEiLCJlbWFpbCI6Imp1bGllbi5iaWVudmVudS1jb3V0YXJlbEBsZWNuYW0ubmV0IiwiZW1haWxfdmVyaWZpZWQiOnRydWUsImV4cCI6MTc3MjQ1MDI2OSwiZmFtaWx5X25hbWUiOiJCaWVudmVudSIsImdpdmVuX25hbWUiOiJKdWxpZW4iLCJncm91cHMiOlsiVVNFUl9PTllYSUEiXSwiaWF0IjoxNzcxODQ1NDY5LCJpc3MiOiJodHRwczovL2F1dGgubGFiLnNzcGNsb3VkLmZyL2F1dGgvcmVhbG1zL3NzcGNsb3VkIiwianRpIjoib25ydHJ0OjEwMDM2OTU3LWRkYjMtNzVlNC01MzQyLThmOTlhZGRjZTQ1OSIsImxvY2FsZSI6ImZyIiwibmFtZSI6Ikp1bGllbiBCaWVudmVudSIsInBvbGljeSI6InN0c29ubHkiLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJqdWxpZW5jbmFtIiwicmVhbG1fYWNjZXNzIjp7InJvbGVzIjpbIm9mZmxpbmVfYWNjZXNzIiwidW1hX2F1dGhvcml6YXRpb24iLCJkZWZhdWx0LXJvbGVzLXNzcGNsb3VkIl19LCJyZXNvdXJjZV9hY2Nlc3MiOnsiYWNjb3VudCI6eyJyb2xlcyI6WyJtYW5hZ2UtYWNjb3VudCIsIm1hbmFnZS1hY2NvdW50LWxpbmtzIiwidmlldy1wcm9maWxlIl19fSwicm9sZXMiOlsib2ZmbGluZV9hY2Nlc3MiLCJ1bWFfYXV0aG9yaXphdGlvbiIsImRlZmF1bHQtcm9sZXMtc3NwY2xvdWQiXSwic2NvcGUiOiJvcGVuaWQgcHJvZmlsZSBncm91cHMgZW1haWwiLCJzaWQiOiIwNGZhNjhhOS04ZGEyLTIyYmUtNDVhOC1hNzg4OWIzOGIwY2IiLCJzdWIiOiIyYTY4YjIyZS1hNWQyLTQyNzctOTczYi03OTQyZjA1NmJlYmIiLCJ0eXAiOiJCZWFyZXIifQ.ZWf81_RKnH2jDX4IJavD5ImLlI7KvYRz16Ijd5gnHitzau-lW_pY78QCBG2F1k9_STp7GdoE-bSP5C4YEKfKJQ')