import boto3
import os
import sys


base_dir = os.path.dirname(os.path.abspath(__file__))
DOWNLOAD_PATH = os.path.join(base_dir, "Texts")
os.makedirs(DOWNLOAD_PATH, exist_ok=True)

import boto3
s3 = boto3.client("s3",endpoint_url = 'https://'+'minio.lab.sspcloud.fr',
                  aws_access_key_id= 'HZBZJ690DLT13479XCD1', 
                  aws_secret_access_key= 'Jk7AQpP+GcS0c0wEl9gfYXSojqmmVZHUniq8vmNM', 
                  aws_session_token = 'eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJhY2Nlc3NLZXkiOiJIWkJaSjY5MERMVDEzNDc5WENEMSIsImFsbG93ZWQtb3JpZ2lucyI6WyIqIl0sImF1ZCI6WyJtaW5pby1kYXRhbm9kZSIsIm9ueXhpYSIsImFjY291bnQiXSwiYXV0aF90aW1lIjoxNzcxOTM3NDY0LCJhenAiOiJvbnl4aWEiLCJlbWFpbCI6Imp1bGllbi5iaWVudmVudS1jb3V0YXJlbEBsZWNuYW0ubmV0IiwiZW1haWxfdmVyaWZpZWQiOnRydWUsImV4cCI6MTc3MzA2MjU2NSwiZmFtaWx5X25hbWUiOiJCaWVudmVudSIsImdpdmVuX25hbWUiOiJKdWxpZW4iLCJncm91cHMiOlsiVVNFUl9PTllYSUEiXSwiaWF0IjoxNzcyNDU3NzY1LCJpc3MiOiJodHRwczovL2F1dGgubGFiLnNzcGNsb3VkLmZyL2F1dGgvcmVhbG1zL3NzcGNsb3VkIiwianRpIjoib25ydHJ0OjNjYjJhYTg2LTgxNGYtNjc4ZS0yZDdhLTRlNjNkMTFjZTZhZSIsImxvY2FsZSI6ImZyIiwibmFtZSI6Ikp1bGllbiBCaWVudmVudSIsInBvbGljeSI6InN0c29ubHkiLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJqdWxpZW5jbmFtIiwicmVhbG1fYWNjZXNzIjp7InJvbGVzIjpbIm9mZmxpbmVfYWNjZXNzIiwidW1hX2F1dGhvcml6YXRpb24iLCJkZWZhdWx0LXJvbGVzLXNzcGNsb3VkIl19LCJyZXNvdXJjZV9hY2Nlc3MiOnsiYWNjb3VudCI6eyJyb2xlcyI6WyJtYW5hZ2UtYWNjb3VudCIsIm1hbmFnZS1hY2NvdW50LWxpbmtzIiwidmlldy1wcm9maWxlIl19fSwicm9sZXMiOlsib2ZmbGluZV9hY2Nlc3MiLCJ1bWFfYXV0aG9yaXphdGlvbiIsImRlZmF1bHQtcm9sZXMtc3NwY2xvdWQiXSwic2NvcGUiOiJvcGVuaWQgcHJvZmlsZSBncm91cHMgZW1haWwiLCJzaWQiOiI2NjkxYWU3NC1iMDhjLWE1ZmUtYjhkMy00OTYwNmQ0YzUxYmUiLCJzdWIiOiIyYTY4YjIyZS1hNWQyLTQyNzctOTczYi03OTQyZjA1NmJlYmIiLCJ0eXAiOiJCZWFyZXIifQ.zzi7ks5FNBAKGNU9QFdnTCItWocia_Ra5wIOXQn91ynAwA6KIb47POVBzJ5nhWTS8kihAjtxUU0mvn6CoqquvA')