import boto3
import os
import sys


base_dir = os.path.dirname(os.path.abspath(__file__))
DOWNLOAD_PATH = os.path.join(base_dir, "Texts")
os.makedirs(DOWNLOAD_PATH, exist_ok=True)

s3 = boto3.client("s3",endpoint_url = 'https://'+'minio.lab.sspcloud.fr',
                  aws_access_key_id= 'HAGRN7LYRHZUFD5RW212', 
                  aws_secret_access_key= '31Ablou69twQKSFxozSujh8VABzD+lTKt0O7vaeY', 
                  aws_session_token = 'eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJhY2Nlc3NLZXkiOiJIQUdSTjdMWVJIWlVGRDVSVzIxMiIsImFsbG93ZWQtb3JpZ2lucyI6WyIqIl0sImF1ZCI6WyJtaW5pby1kYXRhbm9kZSIsIm9ueXhpYSIsImFjY291bnQiXSwiYXV0aF90aW1lIjoxNzcwMzY5Nzk4LCJhenAiOiJvbnl4aWEiLCJlbWFpbCI6Imp1bGllbi5iaWVudmVudS1jb3V0YXJlbEBsZWNuYW0ubmV0IiwiZW1haWxfdmVyaWZpZWQiOnRydWUsImV4cCI6MTc3MTgzODEyNiwiZmFtaWx5X25hbWUiOiJCaWVudmVudSIsImdpdmVuX25hbWUiOiJKdWxpZW4iLCJncm91cHMiOlsiVVNFUl9PTllYSUEiXSwiaWF0IjoxNzcxMjMzMzI2LCJpc3MiOiJodHRwczovL2F1dGgubGFiLnNzcGNsb3VkLmZyL2F1dGgvcmVhbG1zL3NzcGNsb3VkIiwianRpIjoib25ydHJ0OmI2ZGQ5ZTNkLTRiYWEtMDg3NS1jY2YxLWQ5MDM0NWQzMWQzNiIsImxvY2FsZSI6ImZyIiwibmFtZSI6Ikp1bGllbiBCaWVudmVudSIsInBvbGljeSI6InN0c29ubHkiLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJqdWxpZW5jbmFtIiwicmVhbG1fYWNjZXNzIjp7InJvbGVzIjpbIm9mZmxpbmVfYWNjZXNzIiwidW1hX2F1dGhvcml6YXRpb24iLCJkZWZhdWx0LXJvbGVzLXNzcGNsb3VkIl19LCJyZXNvdXJjZV9hY2Nlc3MiOnsiYWNjb3VudCI6eyJyb2xlcyI6WyJtYW5hZ2UtYWNjb3VudCIsIm1hbmFnZS1hY2NvdW50LWxpbmtzIiwidmlldy1wcm9maWxlIl19fSwicm9sZXMiOlsib2ZmbGluZV9hY2Nlc3MiLCJ1bWFfYXV0aG9yaXphdGlvbiIsImRlZmF1bHQtcm9sZXMtc3NwY2xvdWQiXSwic2NvcGUiOiJvcGVuaWQgcHJvZmlsZSBncm91cHMgZW1haWwiLCJzaWQiOiI4M2ZlMTI0MS0wZGZkLTJmMTEtNzE5YS03MGQ2NjVhYzZlYjEiLCJzdWIiOiIyYTY4YjIyZS1hNWQyLTQyNzctOTczYi03OTQyZjA1NmJlYmIiLCJ0eXAiOiJCZWFyZXIifQ.dBJK8FXE5S93GmInpnCT2eTUTnIawOIA7VcERdJeyHezBeDMmXEY7ZXo36vcuQletAKRRb5F4FcdRm8MsWMQ-A')